### ISSUE TITLE
Better syntax group highlighting

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#14]
Look at https://github.com/w0ng/vim-hybrid#screenshots

It even provides highlighting to differentiate between different spell error.

**Comment by NLKNguyen** [comment]
Yes, the group highlighting is definitely what I need to improve. I'll look into the spelling colors. I didn't realize that there are many error spelling types.

**Comment by pickfire** [comment]
> I didn't realize that there are many error spelling types.

Same goes to me at first.

> syntax group highlighting scheme from [Jellybeans](https://github.com/nanotech/jellybeans.vim)

Maybe try to look into jellybeans too as he gets it from jellybeans too.

I think you should also look at colour for **diff**, check **syntax.txt** and provide [lightline](https://github.com/itchyny/lightline.vim) paper color theme as it is faster compare to vim-airline.

**Comment by NLKNguyen** [comment]
I just added 4 types of spell checking colors. Try it out :smiley: 

Since some Syntastic highlighting colors link to 2 of the spell colors, there's an automatic improvement over there too. I won't be focusing on lightline though. The vim-airline theme should provide enough of design guidelines for anyone who wants to port it to lightline. I can't just support all yet-another-status-line plugins out there, especially when I don't even use them in order to understand how to support :)

**Comment by NLKNguyen** [comment]
I'll check out syntax.txt and group highlighting soon.

**Comment by NLKNguyen** [comment]
I improved the group highlighting. I also added Folded color to make it more distinguishable, which I should have done a long time ago :)

**Comment by pickfire** [comment]
I can't try it out as I am still using base16 solarized theme on my terminal.

Is there a color for diff?

**Comment by NLKNguyen** [comment]
You mean vimdiff?

**Comment by pickfire** [comment]
Yeah.

**Comment by NLKNguyen** [comment]
I added it a month ago.

**Comment by pickfire** [comment]
What about **TODO**?

**Comment by NLKNguyen** [comment]
I just added the dark color scheme, and both have highlighting for TODO (see new screenshots) and some improvements for vimdiff. :)

**Comment by pickfire** [comment]
I like the light theme, but the dark color scheme background is a bit too stress for the eyes. I am using the default lightline theme, dejavu mono font.

On the **left**, there is *solarized* and on the **right**, there is *papercolour*. It seems that paper colour has no compatibility for syntax colour between light and dark colour.

I like paper colour as it is compatible the terminal default colourscheme. (no need to source anything when the terminal starts)

![2015-07-09-145648_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8589609/c73bd17e-264a-11e5-8980-0edd48e67452.png)

**Comment by NLKNguyen** [comment]
Can you please go into the file PaperColor-Dark.vim and replace the background color code with one of these (ordered by the increment of brightness) and let me know which one gives the best result in your opinion: 
`let s:background   = "#262626"` 
`let s:background   = "#303030"` 
`let s:background   = "#3a3a3a"` 

About the syntax colors, I use the same for both light and dark. Maybe it's because there are two green colors in the dark version that are kinda close to each other. In the light version, they are red and pink.

**Comment by pickfire** [comment]
I think that the colours for syntax highlighting should be the same, this is for the users who get bored of **light** to switch to **dark** so that they will be easier to switch, example: switching from *solarized* light to *solarized* dark doesn't feel much difference, just the background colour switches, but it is a bit time wasting to switch in solarized unlike paper colour.

![2015-07-09-153322_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8590208/f897af94-2650-11e5-99d0-baa3947a793c.png)

###### Note: top left: solarized, bottom left: #262626, bottom right: #303030, top right: #3a3a3a

In My Humble Opinion, #262626 is better, I am not talking behalf of someone else.

**Comment by NLKNguyen** [comment]
Thanks for your input, I switched the background to #262626 

I did try to retain the light color palette or only alter a bit when designing the dark scheme. That was my original plan, but I couldn't make it to be something I would like because it somehow lacked the feel of Material Design, which is what I'm following, so I went the other route to change the color palette. And yes, I agree that it would be nice if the palette can be similar for both :)

**Comment by pickfire** [comment]
Can paper colour theme use true colors (888 colours)?

Will the dark colour scheme get more improvement? I think that there is a lot of space for the improvement.

And is it difficult to read the text when there is sunlight?

**Comment by NLKNguyen** [comment]
I have no idea about the availability of true colors in different terminals so am not sure if it's a good idea, considering the case of Solarized. I personally don't have a use case where I need true colors yet, so it's not in my plan now.

Sure, there can be improvement. It takes time for me to spend more time actually using it to realize what to improve. Any suggestion is welcome as always.

To read text in sunlight => use light version. That 's my whole goal when I started the light version in the beginning :)

**Comment by pickfire** [comment]
`nvim` support true colors, `vim` doesn't.

> To read text in sunlight => use light version. That 's my whole goal when I started the light version in the beginning :)

I am able to read in sunlight using the solarized dark version.

**Comment by NLKNguyen** [comment]
I plan to make 2 schemes into 1 file, such that

set background=light
color PaperColor

set background=dark
color PaperColor

Do you think it's preferable to having them separate like right now?

**Comment by pickfire** [comment]
Maybe, because I think it will affect the performance. It is just the same thing.

**Comment by pickfire** [comment]
I think when the syntax is almost done, it is time to port **PaperColor** to **base16** or alternative to enable other application to use it.

**Comment by NLKNguyen** [comment]
Yes, it will be in near future.

**Comment by NLKNguyen** [comment]
I start this new project for porting PaperColor to other environments https://github.com/NLKNguyen/papercolor

**Comment by pickfire** [comment]
I think you should saparate each project or you will end up like how solarized is now, unmaintained. And it will take a lot of time to download the whole repository.

**Comment by NLKNguyen** [comment]
Agree. I sent pull requests to a couple of base16 repo for the currently supported environments. Later on, the papercolor repo will mainly contain links to those.

**Comment by pickfire** [comment]
There are some feature that are not in base16, I hope you can add those too while making a pull request to base16. Nowdays, they seem to be less active.
