### ISSUE TITLE
PaperColor-Dark: Dark Green needs some improvement

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#19]
When I look at the **dark green** colour in *PaperColor-Dark*, it is a bit difficult to see.

And do you have support for syntastic? It seems that the error is pink.

**Comment by pickfire** [comment]
And I notice that the **dark theme** is more towards *green*, just like **solarized** is more towards *blue*. Is that what you intended to do?

**Comment by pickfire** [comment]
And the color for **comment** in *PaperColor-Dark* is **green**, should it be **gray**?

I once read an article about color, it said that **blue** is for relaxation, **green** is neutral and **red** is aggressive.

**Comment by Grelek** [comment]
If we both mean [the same color](https://github.com/NLKNguyen/papercolor-theme/blob/master/colors/PaperColor-Dark.vim#L15), by my opinion it's very contrasting and easy to read.

**Comment by pickfire** [comment]
> If we both mean the same color, by my opinion it's very contrasting and easy to read.

What do you mean by that?

**Comment by Grelek** [comment]
> What do you mean by that?

I think the green color doesn't need any improvements or adjustments.

**Comment by pickfire** [comment]
Should I just close this?

**Comment by NLKNguyen** [comment]
The authors of Syntasic link the highlighting against default spelling colors, and there is no local highlighting group for Syntastic to set them individually.

I would like to make the background toward green, but there is 256-color limitation. https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg 
Not all colors are available since this theme needs to work on 256-color terminal. 

The dark green color you mentioned, is it also the comment color? A screenshot may help to clarify.

**Comment by pickfire** [comment]
The terminal now are mostly true colors. Look at https://gist.github.com/XVilka/8346728 and currently only neovim supports it but vim doesn't.

> Parsing ANSI color sequences, but approximating them to 256 palette.

Xterm colors is not so accurate and it depends whether you use xterm. So I think you should look at the color of other terminal.

![2015-07-14-131253_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/8666881/1a873430-2a2a-11e5-8857-99ec6a5d754c.png)

![2015-07-14-131351_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/8666886/3625a104-2a2a-11e5-9625-5a940fd00a98.png)

**Comment by NLKNguyen** [comment]
If that is the case then I will mainly focus on Vim because it's the most common. Neovim still has a very long way to be as ubiquitous as Vim. The same goes for MacVim and other Vim variants. If the theme works fine in Vim, it will work just fine in others, but not vice versa. Also, true color code editor is just not really that important to me for now :)

Yes, it would be nice to take advantage of true color in places where it's available, so anyone is welcome to take it on.

That green color seems okay to me though. I don't know how to make it more readable than it is right now or other colors :)

**Comment by pickfire** [comment]
The dark theme does seems a lot different from the picture and the light theme do have some differences in colors from the README.md:

![2015-07-27-160916_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8901275/3062d002-347a-11e5-95d0-f3a699e56aef.png)

![2015-07-27-161405_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8901344/b3203908-347a-11e5-9536-c0d9dcdd97e8.png)

And how do you make that gif file? Thanks.

**Comment by NLKNguyen** [comment]
The screenshots are usually outdated. I modified some colors since then. I will make some new screenshots at some point. What you have now is as intended (except the indent guides of course).

I used Byzanz software to make the GIF screencast, but I would look for a better alternative. I got the information from [here](http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast).

**Comment by pickfire** [comment]
I think it seems like the colors for the screenshot (some of it) is a bit better than the current status.

**Comment by NLKNguyen** [comment]
Yeah, there are improvements/trials needed for the dark variant. It'll take some time.

**Comment by NLKNguyen** [comment]
I made some small changes of color code in dark variant.

**Comment by pickfire** [comment]
Yeah, it seems like the background is lighter now.
