### ISSUE TITLE
Add colour to operator

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#22]
I hope that *papercolor theme* would have colour on **operators** such as `+`, `=` and `-`.

**Comment by NLKNguyen** [comment]
That unfortunately can't be controlled by any color scheme. I really wish it could, but the syntax files (plugins) for the languages are the ones that decide whether to link the language operators against the standard "operator" highlighting color. 

Most of syntax files just link them to default foreground color. In other words, there is no separate local highlighting group for the operators in order to be set separately from the normal text. Some plugins I listed in the README such as c-syntax.vim or dtrace-syntax-file link them properly, therefore the theme can display them the way you would like. I even tried to convince a syntax file author of a particular language to link those operators to a separate group, but he didn't think that it would be useful.

**Comment by pickfire** [comment]
Yeah, that works but will increase the startup time slightly.
```
2242.301  031.693  031.693: sourcing /usr/share/vim/vim74/syntax/c.vim
2270.851  027.572  027.572: sourcing /home/ivan/.vim/plugged/c-syntax.vim/after/syntax/c.vim
```
Closing.
