### ISSUE TITLE
Clojure support

### ISSUE THREAD

**Issue by shvetsovdm** [NLKNguyen/papercolor-theme#24]
I saw you have clojure syntax highlight but it is commented out. I'll be happy to see clojure support. Do you need some help with testing the syntax?

**Comment by NLKNguyen** [comment]
Yes, I definitely need help on that. I grabbed those highlighting from Tomorrow theme and haven't touched it because it seems big and because Clojure is more foreign to me than any imperative language. 

Would you like to start designing it? and I can join later next weekend when I'll be available for this project. 

I'm currently porting PaperColor to other environments: https://github.com/NLKNguyen/papercolor
You may like to take a look :)

**Comment by shvetsovdm** [comment]
With pleasure.

**Comment by NLKNguyen** [comment]
Merged pull request https://github.com/NLKNguyen/papercolor-theme/pull/25
