### ISSUE TITLE
Tab numbers are hard to read

### ISSUE THREAD

**Issue by mtglsk** [NLKNguyen/papercolor-theme#3]
Aka number of windows in a tab have this grey background against black letters which make them hard to see.

**Comment by NLKNguyen** [comment]
Because Vim automatically bind those tab line colors to some other standard color highlighting of the scheme, they can't be set separately. I recommend to use one of these plugins that customize the tab line for better visual.

Plugin 'https://github.com/bling/vim-airline' 
is the one I used in some of the screenshots. It displays the ordered tab number instead of number of windows, so you can easily do something like 3gt to go to the third tab.

Plugin 'https://github.com/bling/vim-airline'
enhances greatly the status line and tab line, and it retains the number of windows like default. I'm bringing Paper Color theme support to vim-airline very soon. So wait and see :)

Let me know how it works out.

**Comment by NLKNguyen** [comment]
Check out my [blog post](http://wp.me/pp2u4-oB ) for early vim-airline support before my submitted theme get merged into it.
