### ISSUE TITLE
pythonBuiltin highlight groups

### ISSUE THREAD

**Issue by tazimmerman** [NLKNguyen/papercolor-theme#43]
Hi,

Excellent job on the color scheme. It's really pleasant to use.

I just noticed that Python builtin functions (geattr(), dict(), etc.) are not highlighted. Were those omitted on purpose? If so, all I need to do is define something besides foreground in these lines, correct?

  call s:HL("pythonBuiltinFunc", s:foreground, "", "")
  call s:HL("pythonBuiltinObj", s:foreground, "", "")

Thank you

**Comment by tazimmerman** [comment]
This really isn't an issue, and now that I've walked through the color scheme as well as the Python syntax file, I've got things looking pretty nice (thanks to your fine color selections). I added highlighting for pythonDocTest, pythonBuiltinObj and pythonBuiltinFunc.

I did notice that pythonExClass was defined twice -- once as a red, which matches pythonExceptions, and once as orange, which didn't match any exception classes.

I've attached a diff of my changes if you're interested. I would send a pull request but I can't push to Github from my current location.

[PaperColor.diff.txt](https://github.com/NLKNguyen/papercolor-theme/files/40343/PaperColor.diff.txt)

**Comment by NLKNguyen** [comment]
Thanks for that, glad you like it :)
Could you send me a pull request latter on when you get a chance? So I can simply pull it.

As a side note, usually the problem with highlight for builtin function/objects is that the vim syntax file of that language always lacks behind the language specs. So, I tend to make them all as regular text rather than having some highlight correctly and some don't because that can mislead the programmers to think that they made a typo.
