### ISSUE TITLE
Support WildMenu in vim colorscheme.

### ISSUE THREAD

**Issue by jordwalke** [NLKNguyen/papercolor-theme#45]
This seems to be omitted.

**Comment by pickfire** [comment]
Is it? I thought it was there.

**Comment by NLKNguyen** [comment]
I have just added :) 

Before was just auto color group linking. Now it is set manually. Since the WildMenu color group option only allows the color of the current selection to change, the bar color remains the same. And I think it's reasonable because with this setting `set wim=longest:full,full` the WildMenu takes place of the StatusBar.

**Comment by pickfire** [comment]
That's the default for nvim: `set wim=longest:full,full`.

I think I like the old color more, yellow on top of blue. And now it's pink. :(

**Comment by NLKNguyen** [comment]
Oh haha, I can fix that.
How does it look in the dark theme? It was yellow in the dark theme also and wasn't pretty.

**Comment by pickfire** [comment]
That's better, I didn't notice that the dark theme have improved a lot since then.
