### ISSUE TITLE
Add Pascal highlighting

### ISSUE THREAD

**Issue by McSinyx** [NLKNguyen/papercolor-theme#48]
I really like the colorscheme, but unfortunately syntax highlighting fo (Free) Pascal is not available. If you take a look at the screenshot, you can see that functions are not highlighted:

![2016-01-31-161025_724x544_scrot](https://cloud.githubusercontent.com/assets/13689192/12701254/4f30c4ee-c836-11e5-8c73-5e39ab6c36c0.png)

Compare to Solarized:

![2016-01-31-161014_724x544_scrot](https://cloud.githubusercontent.com/assets/13689192/12701262/940be79c-c836-11e5-91f4-118471c88233.png)

Could you please add support for Pascal? Thanks very much.

**Comment by NLKNguyen** [comment]
I have just added Pascal support. Try it out :)

May I ask why and where you use Pascal? I wonder how it is still being used. Last time I saw it was in a high school class more than 10 years ago, and schools already moved on to teach Java and Python, didn't they?

**Comment by McSinyx** [comment]
Thanks! It looks great, but function names and the `begin`, `end`, `var`, `function` things seem to have the same color (electrical blue), which make it not so easy to read.

Well, about the Pascal usage thing, I use it as schools and competitions here (Việt Nam) only allow Pascal and C++, and I didn't learn C++ yet (I wish we could use Python).

Sorry for my bad English anyway.

**Comment by NLKNguyen** [comment]
Don't be sorry about your non-native language :) 

I just changed the function color back to regular text color. The reason is that the Pascal syntax file which comes with Vim simply matches the built-in function names with the text without any context at all. For example, if you declare a variable named `length`, it will match the built-in function `length` even though that would be incorrect. So, I think it's better to not treat them as reserved keywords and just use regular text color for all of the built-in function names. Btw, the syntax file is beyond the scope of a color scheme. I can only provide highlighting colors for the available syntax groups that the syntax file provides.

Ah ha, I come from Viet Nam as well, and I'm surprised that they still use Pascal.

**Comment by pickfire** [comment]
@NLKNguyen Nice, I didn't know you are from Vietnam, I am just in your neighbouring country, Malaysia.

**Comment by NLKNguyen** [comment]
@pickfire Ah, yeah, I noticed :D I moved to the US 6 years ago.
