### ISSUE TITLE
Python syntax coloring: no difference in Boolean values, neither on class (reserved word) and class name

### ISSUE THREAD

**Issue by cuducos** [NLKNguyen/papercolor-theme#53]
As most of the time I use Python, I want to customize `PaperColor` changing two minor details I've seen on other themes such as [molokai](https://github.com/rodnaph/vim-color-schemes/blob/master/colors/molokai.vim), for example:

![PaperColor vs Molokai](http://i.imgur.com/FIg1ilZ.png)

1. Change the color of boolean values (e.g.: the `True` in line 7)
2. Have different colors for `class` reserved word, and for the class name (e.g.: the color of `class` and of `TestFooBar` in line 4)

The file I used there is [this one](https://gist.github.com/cuducos/2723d98fde7b03f7df2e):

```python
from unittest import TestCase


class TestFooBar(TestCase):

    def test_boolean(self):
        variable = True
        self.assertTrue(variable)

    def test_str(self):
        variable = 'foobar'
        self.assertIsInstance(variable, str)

    def test_int(self):
        variable = 42
        self.assertIsInstance(variable, int)
```

I tried to edit the [PaperColor.vim](https://github.com/NLKNguyen/papercolor-theme/blob/master/colors/PaperColor.vim#L764), but it looks like booleans should already be displayed in other color than white:

    call s:HL("pythonBoolean", s:green, "", "bold")

I could not find any call mentioning something related to class names.

Many thanks,

**Comment by NLKNguyen** [comment]
Since the syntax file dictates what syntax groups are available, and it doesn't provide `class` as a separate group name from `def`, the theme can't do much about it. 

From my view, without the extra customization that you have, the Boolean appears as expected. I think your other customization might override the python-syntax plugin. One suggestion I can give is to put the customization before the plugin.

![light](https://cloud.githubusercontent.com/assets/4667129/13068622/118e2160-d432-11e5-8310-671ad17b1204.PNG)
![dark](https://cloud.githubusercontent.com/assets/4667129/13068623/143f56d6-d432-11e5-888b-0b085b6b9e72.PNG)

I intend to make a tutorial for customizing this theme to add language support. I didn't have time to do that, so I just give something that you might find useful now.
 
```
map <silent> <bslash>c :redir @c <bar> echo 'call s:HL("' .  synIDattr(synID(line("."),col("."),1),"name") .
      \ '", s:foreground, "", "")' <bar>redir END<CR>
map <bslash>p "cp<CR>
```
This keymap `\c` will show the syntax group of the word where the cursor is currently at. The code it displays in the command line is the code that this theme expect. It includes a placeholder color.
And the keymap `\p` will paste that line of code to the current buffer. Of course, it is intended to be pasted in PaperColor.vim

These plugins are added to automatically reload the theme every time it is saved.
```
Plugin 'https://github.com/xolox/vim-misc'
Plugin 'https://github.com/xolox/vim-reload'
```

Those are what I use for syntax-group discovery and color design for any language.

**Comment by cuducos** [comment]
Nailed it!

I discovered that PaperColor theme and [rodnaph/vim-color-schemes](https://github.com/rodnaph/vim-color-schemes) might have a conflict for some reason… I commented out the line where I load `vim-color-schemes` and PaperColor worked. Yay.

Many thanks for the `\c` and `\p` scripts. Gonna play with them : )

**Comment by NLKNguyen** [comment]
Great! :+1:
