### ISSUE TITLE
Base16 merge progress

### ISSUE THREAD

**Issue by pickfire** [NLKNguyen/papercolor-theme#6]

**Comment by NLKNguyen** [comment]
Will start in early July and port to a couple of different editors as well :)

**Comment by pickfire** [comment]
I hope you can port it to non-editors as well.

**Comment by NLKNguyen** [comment]
What do you mean?

**Comment by pickfire** [comment]
Other applications that uses the terminal such as mutt, newsbeuter, tmux ...

**Comment by pickfire** [comment]
It doesn't matter now, as long as it is port to base16, it will have colorscheme for these applications too.

**Comment by NLKNguyen** [comment]
Sounds great! :)

**Comment by pickfire** [comment]
I like base16 but there is a downside of base16 too:

You provide the colour platelete but you need to use their **syntax highlighting method** (I can't find a suitable word for it).

**Comment by NLKNguyen** [comment]
Yes, I realized their .erb template files determine the syntax highlighting. That's why I'm not going to make a Vim theme based on Base16 because its syntax highlighting is very limited and doesn't work well on terminal. I'm more interested in releasing the palette to be ported to other places :)

**Comment by pickfire** [comment]
What are you gonna do next?

**Comment by NLKNguyen** [comment]
Nothing changed. I will make a Base16 palette and use it to generate themes for other editors. I had requests for Atom and Sublime Text. And of course anyone can use the palette for other purposes. 

Because the palette must include both light and dark theme, and I didn't design for the dark theme yet, I hold to next month when I will have more free time to explore the colors :) Eventually the Base16 palette and this repo will have the dark theme of Paper Color.

**Comment by pickfire** [comment]
You are doing all by yourselves? I think you need some **collaborator** to help you. I can help you to review *some* merge and issues.

**Comment by NLKNguyen** [comment]
Sure, that would be nice. This repo is kind of subjective design, and there is not much work actually. It's more about personal taste. However, once I make Base16 palette and merge it to Base16-builder, it certainly will be great to have someone to help port it to other places.

**Comment by pickfire** [comment]
I think base16-vim need better syntax highlighting, would you suggest a better syntax highlighting for them? https://github.com/chriskempson/base16-vim/issues

**Comment by pickfire** [comment]
I think the papercolor theme for vim airline should have different colour for different mode to notify the users. What do you think?

**Comment by NLKNguyen** [comment]
I thought of that, but I think once I try build with Base16, I will have a better idea about the whole thing. But right now I don't think much about Base16-vim because the generated vim theme doesn't behave well on terminal, which is a deal breaker.

About vim-airline, I particularly don't like the way other themes do because I think they draw too much unnecessary attention to the status line, which I think is not the important thing to pay attention to. I think the code should be the focal point of interest, not the status line. Flashing status colors seems very distracting, especially to someone who looks at your screen. I believe any intermediate Vim user has no problem knowing what the current mode is without the explicit guidance of the status line.  :)

**Comment by pickfire** [comment]
> About vim-airline, I particularly don't like the way other themes do because I think they draw too much unnecessary attention to the status line, which I think is not the important thing to pay attention to. I think the code should be the focal point of interest, not the status line. Flashing status colors seems very distracting, especially to someone who looks at your screen. I believe any intermediate Vim user has no problem knowing what the current mode is without the explicit guidance of the status line. :)

I think beginners should be suggested to take `light` theme first. I suggest to add description in *README.md* for papercolor theme to be **less distractive**.

If you doesn't go with Base16, then you would make this the base repository for papercolor theme just like solarized? Or split it up into different repository just like what the solarized do now (maybe regretted)?

**Comment by NLKNguyen** [comment]
I wouldn't suggest that because people have different opinions :)

As I told you, I will make Base16 palette. I just don't use it to generate Vim theme. It can be used to generate other themes.

**Comment by pickfire** [comment]
> As I told you, I will make Base16 palette. I just don't use it to generate Vim theme. It can be used to generate other themes.

It will generate all theme that it can generate including vim.

**Comment by pickfire** [comment]
To generate a theme for base16 just list out the 8 accent colors and 6 (if I am right) tone colors. So that is why solarized colors using base16 is a bit off because it uses 8 tone colors.

**Comment by NLKNguyen** [comment]
All I meant is that I don't need the Vim theme generated from the builder because this repo is more optimal. I'm interested in using that builder to bring this scheme to other places. I'll take a deeper look at the builder later when I start working on that :)
