### ISSUE TITLE
Airline theme name

### ISSUE THREAD

**Issue by groigc** [NLKNguyen/papercolor-theme#7]
If the airline theme is renamed from papercolor to PaperColor (the file and all ocurrences of papercolor inside the code) then `let g:airline_theme='papercolor'` would not be necessary.

**Comment by NLKNguyen** [comment]
That would be a good idea. I firstly started with lowercase because it's vim-airline's theme name convention, so I just followed the flow. It's now merged to vim-airline. The local vim-airline theme in this repo however doesn't have to follow any convention, so yes, it would be better to change it to match the color scheme name like you said. I will do it this weekend. Thanks for suggesting :)

**Comment by groigc** [comment]
I'd make a pull request, but I'm not able to clone/pull/push anything from github right now.  Nice work with this colorscheme, btw. Is the only light colorscheme that caught my attention.

**Comment by NLKNguyen** [comment]
Yes, please send a pull request :) Very glad you like this scheme :smile:

**Comment by groigc** [comment]
Pull request sent.
