### ISSUE TITLE
distribute with Vim?

### ISSUE THREAD

**Issue by chrisbra** [NLKNguyen/papercolor-theme#99]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by NLKNguyen** [comment]
I would love to see this color scheme distributed with Vim. You got my permission.

Currently this works identically for true color & 256-color, and it doesn't need more than 256-color. It also supports 8-color and 16-color by using the terminal colors, targeting default terminal color palette as seen in Windows Command Prompt or Mac Terminal. 

Changing the terminal color palette will yield almost the same visual as 256-color, for example, https://github.com/NLKNguyen/papercolor-theme/issues/71#issuecomment-234128705 for dark version on Windows Command Prompt. Some revisions might have taken since then, and there can be improvements, but I don't see requests for supporting less than 256-color.

**Comment by chrisbra** [comment]
Great.

Well, I can collect your file and send it to Bram, or you can do it. I would prefer if you can do it, since you know obviously best, when it is kind of stable enough and of course you will know when to send updated themes to Bram for inclusion. If you would like to do it mention that this is for issue 1665 to fix it. thanks!

**Comment by pickfire** [comment]
+1 to distributing more colorschemes but it's kinda slow to load papercolor theme.

**Comment by NLKNguyen** [comment]
@pickfire Once it gets close to version 1.0, I will focus on optimization. Unfortunately, the progress is slow. I have another project https://github.com/NLKNguyen/papercolor-vim-precompiler to compile this PaperColor.vim to fast barebone highlight instructions without anything in between (well, probably 1 or 2 if-branches). The disadvantage is that the file size gets bigger, and the customization option will not have effect. Also, it is rather read-only. Might be in the future it can become more useful than it is now.

@chrisbra I can do that. I got a question though. How do you suggest to resolve the color scheme name conflict between the one that comes with the distribution and the one users obtain online that has the same name?

**Comment by chrisbra** [comment]
I don't think there is a problem. If there are several colorschemes with the same name, I believe the one earlier in the runtime path will be picked (which would usually be the one in ~/.vim/ rather then /usr/share/vim/vim80)

**Comment by NLKNguyen** [comment]
@chrisbra I see. Cool. I'll send it to Bram. Thanks for the coordination work 😄

**Comment by NLKNguyen** [comment]
The loading time is reduced a lot now. Please check again @pickfire 

@chrisbra is there a window time for theme submission to Bram for next Vim release? I would like to improve the theme further before sending to him.

**Comment by chrisbra** [comment]
no, don't know.

**Comment by pickfire** [comment]
@NLKNguyen Yup, definitely a lot faster now compared to back then (but still the slowest file loaded on startup). It just appears, `nvim` startuptime shows:

    041.297  017.320  016.931: sourcing /home/ivan/.config/nvim/plugged/papercolor-theme/colors/PaperColor.vim

**Comment by NLKNguyen** [comment]
It just has another major refactor for speed. Please check @pickfire 
From what I see, the current speed is compatible with gruvbox, which was faster than the old version of PaperColor that doing much less than it is now  https://github.com/NLKNguyen/papercolor-theme/issues/28.

**Comment by pickfire** [comment]
Wow, now it's almost a 10x improvement over the original version. On my laptop:

    030.737  007.281  006.893: sourcing /home/ivan/.config/nvim/plugged/papercolor-theme/colors/PaperColor.vim

But on raspberry pi 2 there is noticable speed difference:

    350.376  095.841  091.063: sourcing /home/ivan/.config/nvim/plugged/papercolor-theme/colors/PaperColor.vim

But kinda still looks cool that filetype.vim load even slower than papercolor theme:

    244.914  156.993  156.605: sourcing /usr/share/nvim/runtime/filetype.vim

@NLKNguyen Great job on the 10x optimazations. 👍

**Comment by NLKNguyen** [comment]
😄 Glad it turned out well. I had to learn Sed script to do the code transformation because the amount of code to be changed was huge. I'm actually surprised by the fact that it can be this fast despite doing a ton. The speed was a major concern as this theme becoming a framework for color themes, but now it is fine.
